{"name": "Crear un usuario nuevo y restablecer la contraseña", "status": "failed", "statusDetails": {"message": "AssertionError: El usuario nuevo_usuario@example.com no fue creado correctamente\n", "trace": "  File \"C:\\Users\\Didier Ortega\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Didier Ortega\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\restablecimiento_contrasena.py\", line 41, in step_impl\n    assert response.status_code == 200, f\"El usuario {email} no fue creado correctamente\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "steps": [{"name": "Given el correo \"nuevo_usuario@example.com\" no existe en el sistema", "status": "passed", "start": 1727130152148, "stop": 1727130152152}, {"name": "When el usuario solicita restablecer la contraseña para \"nuevo_usuario@example.com\"", "status": "passed", "start": 1727130152152, "stop": 1727130152169}, {"name": "Then el sistema crea un nuevo usuario con el correo \"nuevo_usuario@example.com\"", "status": "failed", "statusDetails": {"message": "AssertionError: El usuario nuevo_usuario@example.com no fue creado correctamente\n", "trace": "  File \"C:\\Users\\Didier Ortega\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"C:\\Users\\Didier Ortega\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python312\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\restablecimiento_contrasena.py\", line 41, in step_impl\n    assert response.status_code == 200, f\"El usuario {email} no fue creado correctamente\"\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n"}, "start": 1727130152169, "stop": 1727130152186}, {"name": "And el sistema envía un enlace de restablecimiento al correo \"nuevo_usuario@example.com\"", "status": "skipped", "start": 1727130152193, "stop": 1727130152193}], "start": 1727130152136, "stop": 1727130152193, "uuid": "e4d04863-7596-48a3-9b4d-a8b7a0320caf", "historyId": "d53d092cf88c306a5f12367ffdbe94b0", "fullName": "Restablecimiento de contraseña de usuario: Crear un usuario nuevo y restablecer la contraseña", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "Restablecimiento de contraseña de usuario"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}